# Generated by Django 2.0.4 on 2019-01-30 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180919_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 9, 57, 9, 659675)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 9, 57, 9, 659675)),
        ),
    ]
