# Generated by Django 2.0.4 on 2018-12-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180919_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 16, 15, 16, 487218)),
        ),
    ]
