# Generated by Django 2.0.4 on 2019-02-08 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20190130_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_lecture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 17, 2, 31, 499843)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 17, 2, 31, 499843)),
        ),
    ]
